/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenge05;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      System.out.println(new App().getGreeting());
      Node newNode = new Node(5);
      LinkedList newList = new LinkedList();
      newList.insert(8);
      System.out.println(newList.toString());
    }
}
