/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenge05;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void toStringReturnsString(){
      Node newNode = new Node(5);
      LinkedList newList = new LinkedList();
      newList.insert(8);
      System.out.println(newList.toString());
    }
}
