/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datastructures;

import datastructures.linkedlist.LinkedList;
import datastructures.linkedlist.Node;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LinkListTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void includesReturnsNodeValue(){
      LinkedList newList = new LinkedList();
      for(int i = 1; i <= 5; i++){
        newList.insert(i);
      }
      assertTrue(newList.includes(5));
    }

    @Test void toStringReturnsString(){
      Node newNode = new Node(5);
      LinkedList newList = new LinkedList();
      newList.insert(8);
      newList.insert(4);
      assertEquals(newList.toString(), "[8]->[4]->NULL");
    }


}
